// Application constants for Clinical Trials Data Collector

export const APP_CONFIG = {
  NAME: 'ClinicalTrialsDataCollector',
  VERSION: '1.0.0',
  DESCRIPTION: 'Backend system for clinical trials data collection and management'
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500
};

export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  RESEARCHER: 'RESEARCHER',
  COORDINATOR: 'COORDINATOR',
  DATA_ENTRY: 'DATA_ENTRY',
  VIEWER: 'VIEWER'
};

export const USER_STATUS = {
  ACTIVE: 1,
  INACTIVE: 0,
  SUSPENDED: 2,
  PENDING: 3
};

export const TRIAL_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  RECRUITING: 'RECRUITING',
  SUSPENDED: 'SUSPENDED',
  COMPLETED: 'COMPLETED',
  TERMINATED: 'TERMINATED'
};

export const PATIENT_STATUS = {
  ENROLLED: 'ENROLLED',
  SCREENING: 'SCREENING',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  WITHDRAWN: 'WITHDRAWN',
  DISCONTINUED: 'DISCONTINUED'
};

export const ADVERSE_EVENT_SEVERITY = {
  MILD: 'MILD',
  MODERATE: 'MODERATE',
  SEVERE: 'SEVERE',
  LIFE_THREATENING: 'LIFE_THREATENING',
  FATAL: 'FATAL'
};

export const ADVERSE_EVENT_RELATIONSHIP = {
  UNRELATED: 'UNRELATED',
  UNLIKELY: 'UNLIKELY',
  POSSIBLE: 'POSSIBLE',
  PROBABLE: 'PROBABLE',
  DEFINITE: 'DEFINITE'
};

export const FORM_STATUS = {
  DRAFT: 'DRAFT',
  COMPLETED: 'COMPLETED',
  VERIFIED: 'VERIFIED',
  LOCKED: 'LOCKED'
};

export const AUDIT_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  VIEW: 'VIEW',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  EXPORT: 'EXPORT'
};

export const DOCUMENT_TYPES = {
  PROTOCOL: 'PROTOCOL',
  CONSENT_FORM: 'CONSENT_FORM',
  CASE_REPORT_FORM: 'CASE_REPORT_FORM',
  ADVERSE_EVENT_REPORT: 'ADVERSE_EVENT_REPORT',
  REGULATORY_DOCUMENT: 'REGULATORY_DOCUMENT',
  OTHER: 'OTHER'
};

export const EXPORT_FORMATS = {
  CSV: 'CSV',
  EXCEL: 'EXCEL',
  PDF: 'PDF',
  JSON: 'JSON'
};

export const NOTIFICATION_TYPES = {
  ADVERSE_EVENT: 'ADVERSE_EVENT',
  PATIENT_ENROLLMENT: 'PATIENT_ENROLLMENT',
  FORM_COMPLETION: 'FORM_COMPLETION',
  REGULATORY_DEADLINE: 'REGULATORY_DEADLINE',
  SYSTEM_ALERT: 'SYSTEM_ALERT'
};

export const JWT_CONFIG = {
  ACCESS_TOKEN_EXPIRY: '15m',
  REFRESH_TOKEN_EXPIRY: '7d',
  ALGORITHM: 'HS256'
};

export const PAGINATION = {
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
  DEFAULT_OFFSET: 0
};

export const FILE_UPLOAD = {
  MAX_SIZE: 10 * 1024 * 1024, // 10MB
  ALLOWED_TYPES: ['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'csv', 'xlsx'],
  UPLOAD_PATH: 'uploads/'
};

export const VALIDATION_RULES = {
  PASSWORD_MIN_LENGTH: 8,
  USERNAME_MIN_LENGTH: 3,
  EMAIL_REGEX: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  PHONE_REGEX: /^\+?[\d\s\-\(\)]+$/
};

export const CACHE_KEYS = {
  USER_PERMISSIONS: 'user_permissions',
  TRIAL_DATA: 'trial_data',
  PATIENT_DATA: 'patient_data',
  FORM_TEMPLATES: 'form_templates'
};

export const CACHE_TTL = {
  SHORT: 300, // 5 minutes
  MEDIUM: 1800, // 30 minutes
  LONG: 3600 // 1 hour
};

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  DUPLICATE_ERROR: 'DUPLICATE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};

export const REGULATORY_REQUIREMENTS = {
  GCP_COMPLIANCE: 'GCP_COMPLIANCE',
  FDA_COMPLIANCE: 'FDA_COMPLIANCE',
  EMA_COMPLIANCE: 'EMA_COMPLIANCE',
  ICH_COMPLIANCE: 'ICH_COMPLIANCE'
};

const constants = {
  APP_CONFIG,
  HTTP_STATUS,
  USER_ROLES,
  USER_STATUS,
  TRIAL_STATUS,
  PATIENT_STATUS,
  ADVERSE_EVENT_SEVERITY,
  ADVERSE_EVENT_RELATIONSHIP,
  FORM_STATUS,
  AUDIT_ACTIONS,
  DOCUMENT_TYPES,
  EXPORT_FORMATS,
  NOTIFICATION_TYPES,
  JWT_CONFIG,
  PAGINATION,
  FILE_UPLOAD,
  VALIDATION_RULES,
  CACHE_KEYS,
  CACHE_TTL,
  ERROR_CODES,
  REGULATORY_REQUIREMENTS
};

export default constants;
